### ISSUE TITLE
Cache the image after first time loading

### ISSUE THREAD

**Issue by iozeey** [payalord/xZoom#12]
Hi,
First of all thanks for sharing your useful code to public.

Now its actually needed a feature .

When you hove over big image container for zoom it generates request for preview image.
I want it to be like this load image only for first time then cache the image for again user interaction with same image.

Thanks

**Comment by payalord** [comment]
As I saw, usually browser is caching the images himself, after first time loading. Make sure, that your browser cache is not switched off, because while you in development process maybe you switched it off. If this not helps you and you need more than this with images caching, then we can discuss more details on this.

**Comment by ermushko** [comment]
Even mobile safari does the trick. Maybe opened Devtools can disable caching while you're testing?
