### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by Novadahoozer** [payalord/xZoom#24]
Hey
I am runing into this error on mobile but it works fine on desktop
Uncaught TypeError: $(...).hammer is not a function
    at HTMLImageElement.<anonymous> (setup.js:21)
    at Function.each (jquery.min.js:2)
    at n.fn.init.each (jquery.min.js:2)
    at HTMLDocument.<anonymous> (setup.js:19)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.K (jquery.min.js:2)
(anonymous) @ setup.js:21
each @ jquery.min.js:2
each @ jquery.min.js:2
(anonymous) @ setup.js:19
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
K @ jquery.min.js:2
 here is a link http://urbanbrains.co.za/evesport/product_page.html

**Comment by Novadahoozer** [comment]
Hey i did solve this issue dont do the mistake i did you need to run your jquery before you run hammer.js and setup.js if you run your setup.js and hammer.js before you run your jquery you will have issues.
the only problem i have is that the zoom does not want to work on mobile plus it resizes the container bigger then when you scroll done it resizes the image to the right size.

**Comment by Novadahoozer** [comment]
when i have it open on desktop it works fine the moment i go to mobile it gos out of proportion and i get this [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

what is the solution to fix this

**Comment by payalord** [comment]
On this particular page: http://urbanbrains.co.za/evesport/product_page.html the link to jquery.hammer.min.js is broken and returns 404 not found.

But, the problem looks like exists with some mobile proportions. I'll check this today and make couple tests. Later will let you know here. Thanks.

**Comment by Novadahoozer** [comment]
Hey i am looking at the code and hammer.js is been loaded i am not getting any errors?
also the zoom does not work on mobile is there a way to fix this please give me a solution for this asap?

Thank you

**Comment by payalord** [comment]
I can help you, but I need a little more time to analyze this issue. And yeah now I see that hammer loads fine on that page.

Somehow it works on this page: https://payalord.github.io/xZoom/ so I think the problem is not related exactly hammer.js or xZoom, but related compatibility with another scripts or css that you are using on the page, which affecting same field of events or elements which cause that side effect of broken zoom. For example, on one of previous [issue](https://github.com/payalord/xZoom/issues/5) we had problem with foundation transition styles on images that caused slow movement of lens.
